name: NOAIPrep
options:
  bundleIdPrefix: com.noaiprep
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  DEVELOPMENT_TEAM: "8PP4GN4JBD"
  SWIFT_VERSION: "6.0"
  CODE_SIGN_STYLE: "Automatic"
  GENERATE_INFOPLIST_FILE: YES
  INFOPLIST_FILE: NOAIPrep/Resources/Info.plist

targets:
  NOAIPrep:
    type: application
    platform: iOS
    sources:
      - path: NOAIPrep
        excludes:
          - "**/*.json"
    resources:
      - path: NOAIPrep/Resources/Assets.xcassets
      - path: NOAIPrep/Data
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.noaiprep.app
      PRODUCT_NAME: "NOAI Prep"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    info:
      path: NOAIPrep/Resources/Info.plist
      properties:
        CFBundleDisplayName: "NOAI Prep"
        UILaunchScreen: {}
